from django.core.exceptions import ObjectDoesNotExist




from celery import shared_task



